### ISSUE TITLE
달력 선택이 미쳤다?

### ISSUE THREAD

**Issue by perzona420** [bjrambo/attendance#40]
@bjrambo 
달력아이콘을 눌러서 날짜를 선택하세요   [2016-01-04] 흐흐흠..
라이믹스에서 나는 오류인지 순정 XE에도 나오는지 모르겠지만..

맛이 간 것 같아요. 달력이.. 계속 엉뚱하게 1월로 가네요.

그리고 attendance_monthly에서 값을 불러올 때 중복된 기록(다른 달의 출석 내역) 때문에 
DB::getInstance(); 이용해서 불러오면 값이 0으로만 표기됩니다. (member_srl 하나인 경우에만 정상)

ps. 여기서 '중복된 기록'이란 regdate 날짜는 다르지만 같은 member_srl인 경우를 의미

**Comment by bjrambo** [comment]
제목은, 알아보기 쉽게..

내용은 어디 위치의 달력인지 등등의 상세하게좀요..

**Comment by perzona420** [comment]
@bjrambo 으음.. 관리자 페이지 상단에 있는 달력 '날짜를 선택하세요'부분입니다.
적절한 제목이 떠 오르지 않네요. 가능한 쉽게 서술하려고 했는데.. 관련해서 이미지로 좀 있다 다시 정리하겠습니다.

**Comment by bjrambo** [comment]
@perzona420 라이믹스 이슈입니다.

**Comment by perzona420** [comment]
@bjrambo 역시 그렇군요.
2번째 부분에 대한 설명은 제가 썻어도 이해가 안될 것 같아서 이미지로 다시 설명할게요 ㅠㅠ

제 사이트에서 '이번달 출석수'를 게시판 스킨에서 아래처럼 불러오는데,
<img src="http://i.imgur.com/cDRXdUq.jpg?1">
작은 문제가 있습니다. 관리자가 임의로 '다른 달(과거나 미래나)'에 출석을 찍어버리면..
<img src="http://i.imgur.com/6GxhttL.jpg?1">
이렇게 2개가 생성됩니다. (네, 물론 각각 생성되는 게 맞는거죠)

하지만.. 2개 생성 되면 그때 부터 인식이 불가능한 것 같아요.
그래서 이번달 출석이 0으로 출력됩니다.
<img src="http://i.imgur.com/M4WrvAz.jpg?1">

`$query = $oDB->_query('select * from rx_attendance_monthly where member_srl ='.$oDocument->get('member_srl'));`
통해서 단순히 불러왔습니다. 어떻게 작성해야 이번달 부분만 인식해서 출력할까요?
감사합니다.
