### ISSUE TITLE
php 7.0 에서 월간개근시작일 설정 저장이 안되는 문제.

### ISSUE THREAD

**Issue by kanxion** [bjrambo/attendance#41]
php 7.0 에서 월간개근시작일 설정 저장이 안되는 문제가 있습니다.

**Comment by bjrambo** [comment]
해당기능은 지원이 종료되었습니다.

**Comment by bjrambo** [comment]
https://github.com/bjrambo/attendance/commit/8983520b0df4c0fb0dd55196cee6888b6570992b
