### ISSUE TITLE
출석정보를 회원정보에 반영토록..

### ISSUE THREAD

**Issue by Jobdeok** [bjrambo/attendance#46]
회원정보보기나 로그인 위젯 또는 레이아웃에서 출석정보에 대한 표현이 가능토록 개선을 요청합니다.
- 총 ?일 출석하셨습니다.
- 주 개근 횟수 ?회
- 월 개근 횟수 ?회
- 주(월) 개근중입니다. or 주(월) 개근에 실패하셨습니다.
- 결석 ?일
- 출석 ?일 / 365일
- 주 ?등 / 월 ?등 / 총 ? 등 
- 최근 출석 시각

등 다양한 정보를 출력해길 바랍니다.

**Comment by bjrambo** [comment]
다음달 초 주말부터 작업예정

**Comment by bjrambo** [comment]
Add to member attendance info page in https://github.com/bjrambo/attendance/commit/32df1fef7c9f95c671afc523679bf19289fc2af3
