### ISSUE TITLE
자동출석에 대한 개선의견

### ISSUE THREAD

**Issue by Jobdeok** [bjrambo/attendance#47]
현재 자동출석여부를 관리자가 할 수 있도록 되어 있는데 이 부분을
1. 관리자가 자동출석기능을 ON/OFF 할수 있도록 한다.
2. 자동출석기능이 ON일 경우 개인별 회원정보란에 자동출석 ON/OFF에 대한 부분이 표시된다.
3. 자동출석시에 "인사말" 을 개인별로 설정할 수 있도록 한다.
4. 인사말은 1개 이상시 랜덤 / 순차적으로 작동 될수 있도록 설정한다.
5. 자동출석시에 쪽지나 알림센터로 출석됨을 알린다.

자동출석에 대한 개인의 의사를 존중해주면서 편의성을 높인 방안입니다.
물론 개발은 어렵겠지만 좋은 방법인듯하여 의견을 남겨봅니다.

**Comment by bjrambo** [comment]
@kaijess 개인 커뮤니티 상황에서는 이 항목은 쓸만할것 같기도한데.. 현재쿼리에서 좀 맣은 쿼리를 불러오면 타임아웃이나 문제가 될 우려가 될것 같아서 조금 고민해보겠어요.

**Comment by kaijess** [comment]
@bjrambo 고민해 보라고 올렸습니다 ㅋ
