### ISSUE TITLE
7.0.1 패치후 등수상관없이 1등 추가 포인트가 모두 지급되는 문제가 있습니다.

### ISSUE THREAD

**Issue by botserv** [bjrambo/attendance#48]
php5.3 xe 1.7.X 버전 이용자인데

7.0.1 이후 패치후 등수 상관없이 1등 포인트가 추가적으로 모두 지급되네요:(

**Comment by bjrambo** [comment]
문제가 되는 서버를 제 이메일 qw5414@naver.com 으로 정보를 주시면 알아보도록 해볼께요.

ftp정보 및, xe사이트, xe관리자 계정 정보를 알려주셔야 합니다.

**Comment by bjrambo** [comment]
22일이나 지났음에도 피드백이 없어서 이슈 닫습니다.
