### ISSUE TITLE
수동 설치시 모듈에서 인식을 못합니다.

### ISSUE THREAD

**Issue by happyhg3927** [bjrambo/attendance#51]
자동 설치 문제로 수동 설치를 하고 모듈 폴더에 넣었는데,
전혀 인식을 못합니다.
어떻게 해결해야 할까요?

**Comment by bjrambo** [comment]
modules/attendance 에 attendance 폴더를 넣은것이 아닌지 확인해보세요.

실제로 attendance 에 conf폴더부터 attendance.view.php 파일까지 압축이 풀려있어야 정상적인 설치가 완료된 것입니다.

단순히 수동설치의 방법이 정확하게 개발진이 파악하지 않는이상 도움을 크게 드리기가 어려운점 양해 부탁드립니다.

**Comment by happyhg3927** [comment]
네, htdocs/modules/attendance에 모든 파일 넣었습니다.

conf 폴더부터 attendance.view.php 까지 있습니다.

다만 XE CMS 고급설정 > 모듈에서 인식을 못합니다. ㅠㅠ

게시판 생성에서도 인식을 못하구요.

왜 이러는지..

수동설치 방법은 Filezilla 클라이언트로 압축파일에서 파일 전체 선택 후 드래그 앤 드롭 했습니다.

**Comment by bjrambo** [comment]
어제 답변을 남겨드렸다 시피 정상적인 설치를 하게되면 설치가 인식안되지 않습니다.

어떤 상태의 설치를 진행되어있는지 직접 이미지캡처를 통해서 알려주지 않으면..확인이 안될것 같아요.

**Comment by happyhg3927** [comment]
약 12번의 재설치 끝에 해결되었습니다..
원인은 압축파일 손상에 있었습니다. 감사합니다.
