### ISSUE TITLE
출석확인창에서 취소선택후 출석불가

### ISSUE THREAD

**Issue by realgood253** [bjrambo/attendance#52]
XETOWN 출석부에서 크롬,오페라 브라우저로 테스트해봤습니다.

상황
1. 인사말을 작성하고 출석버튼 클릭
2. "출석하시겠습니까?" 확인창이 나오면 **취소** 
3. 출석버튼을 재클릭
4. "중복출석 방지를 위해 한 번만 눌러주세요." 라는 메세지 출력되고 출석은 되지 않음.
5. 새로고침하기전까진 출석버튼을 눌러도 4가 반복됨

인사말을 수정하려고 취소를 했다가 발견했습니다만 
인사말수정여부와는 상관없이 2번상황에서 취소버튼을 누르면 
새로고침 전까진 출석이 불가능한것 같습니다.

**Comment by bjrambo** [comment]
최신버전의 스킨에서는 해당 부분을 다른 방식을 사용하기때문에 해당되지 않습니다.
