### ISSUE TITLE
모바일 스킨에 제거해야 할 것이 있습니다.

### ISSUE THREAD

**Issue by wookho** [bjrambo/attendance#56]
{@ Context::addJsFile("./common/js/jquery.js", true, '', -100000) }
{@ Context::addJsFile("./common/js/js_app.js", true, '', -100000) }
{@ Context::addJsFile("./common/js/common.js", true, '', -100000) }
{@ Context::addJsFile("./common/js/xml_handler.js", true, '', -100000) }
{@ Context::addJsFile("./common/js/xml_js_filter.js", true, '', -100000) }

헤더 부분에 이게 아직 남아있네요~

**Comment by bjrambo** [comment]
Fixed in https://github.com/bjrambo/attendance/commit/c440dc50e1a9062ded7693583d3dc3f3ef69dc91
