### ISSUE TITLE
존재하지 않는 함수 modifyColumn 사용

### ISSUE THREAD

**Issue by YJSoft** [bjrambo/attendance#73]
https://github.com/bjrambo/attendance/blob/97fc2458594655df7753f22ed6e78202fc05d0d8/attendance.class.php#L236

modifyColumn 함수는 XE에 없습니다. xpressengine/xe-core#901 에서 논의되던 기능이나 실제 추가되지 않았습니다.

**Comment by bjrambo** [comment]
예전부터 알고 있엇는데 시간때문에 제거하지 못하고 있엇어요 ㅇ_ㅇ;; 얼른 코드 빼놔야할것 같은데.. 문제는 ipv6 로 출석되는 경우ㄷ가 많아 DB저장 데이터가 문제가 되는경우가 좀 있어서 난감하네요.

XE측에서 지원해줫으면 좋겠는데 ㅡ,.ㅡ;

**Comment by bjrambo** [comment]
Fixed in https://github.com/bjrambo/attendance/commit/b349d0eb267cf4b435c109da508724c5df220288
