### ISSUE TITLE
출석 진행시 트리거 추가

### ISSUE THREAD

**Issue by nemo9l** [bjrambo/attendance#74]
insertAttendance 에 대한 트리거가 추가되었으면 좋겠습니다.

애드온이나 모듈 등에서 끼어들 여지가 없다는 점이 많이 불편합니다ㅠ

물론 애드온에서 act 값을 확인하여 가로채는 방법도 있겠지만, 트리거라는 좋은 기능이 있는데 활용하지 않는것도 바보같은 짓이 아닌가 싶네요.

**Comment by bjrambo** [comment]
https://github.com/bjrambo/attendance/blob/master/attendance.controller.php#L465

🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣

**Comment by nemo9l** [comment]
아, after 에 대한 트리거는 이미 존재했었군요.

제가 필요한 부분은 before 이다보니, 정확하게 명시를 하지 못했던거 같습니다.
