### ISSUE TITLE
특수문자가 포함된 출석체크 이후 이미 출석했다고 처리되는 문제

### ISSUE THREAD

**Issue by nemo9l** [bjrambo/attendance#76]
#, ^ 문자가 포함된 인삿말로 출석 진행시
해당 문자가 포함된 경우 출석을 진행할 수 없다고 나옵니다.
이후 다시 출석을 시도할 경우, 이미 출석되었다고 출력됩니다.

attendance.controller.php L125~L128

**Comment by bjrambo** [comment]
Fixed https://github.com/bjrambo/attendance/commit/353106a3eac684b2bf269970d896c80e8fb11a7e
