### ISSUE TITLE
코어 2.0.6 이후로 모바일 반응형의 템플릿 로딩 문제

### ISSUE THREAD

**Issue by cydemo** [bjrambo/attendance#80]
지난번 코어에서 page모듈의 반응형 사용시 템플릿 문제도 그렇고,
https://github.com/rhymix/rhymix/commit/9cac59095ba5023d95c77264571a04b8343ae878

확실하진 않지만 다른 서드파티에서도 템플릿 경로 관련해서 이슈가 있어서 제보드립니다.
https://xetown.com/questions/1519785#comment_1524337

**Comment by bjrambo** [comment]
XE호환성을 위해서 우선은 기존 설정을 유지합니다.
